name: Validate PR Structure 🔍

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  PrValidation:
    name: Validate PR Structure 🔍
    secrets: inherit # pragma: allowlist secrets
    uses: V-tal/shared-workflows/.github/workflows/pr-validation.yml@main
