name: Pre Commit Hooks 🧰

on: [pull_request]

permissions:
  contents: read
  actions: read

jobs:
  PreCommitHooks:
    name: Pre Commit Hooks 🧰
    secrets: inherit # pragma: allowlist secrets
    uses: V-tal/shared-workflows/.github/workflows/pre-commit.yml@main
