name: Release Flow 🚀

on:
  workflow_dispatch: {}
  create:
    branches:
      - "release/**"

  pull_request:
    branches: ["main", "release/**"]
    types: [opened, reopened, synchronize, ready_for_review, closed]
  push:
    branches:
      - "release/**"

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  validate:
    name: Guard 🛡️
    if: >-
      ${{
        !(
          github.event_name == 'push' &&
          github.event.created == true &&
          startsWith(github.ref_name, 'release/')
        )
      }}
    uses: V-tal/shared-workflows/.github/workflows/check-rules.yml@main
    secrets: inherit # pragma: allowlist secret
    with:
      runs_on: '["self-hosted","dev"]'
      trigger_event_name: ${{ github.event_name }}
      push_created: ${{ (github.event_name == 'push' && github.event.created) || false }}
      main_branch: "main"
      release_prefix: "release/"
      feature_prefix: "feature/"
      bugfix_prefix: "bugfix/"
      hotfix_prefix: "hotfix/"
      ignore_bot_prs: true
      allow_workflow_dispatch: true

  sonar:
    name: SonarQube Scan 🔍
    needs: [validate]
    if: >-
      ${{
        needs.validate.result == 'success' &&
        needs.validate.outputs.should_run_sonar == 'true'
      }}
    secrets: inherit # pragma: allowlist secret
    uses: V-tal/shared-workflows/.github/workflows/sonar-node.yml@main
    with:
      runs_on: '["self-hosted","dev"]'
      node-version: "20"
      context: "."
      unit_tests_enabled: true
      coverage_required: true
      sonar_enabled: true
      sonar_project_name: "ms-resource-catalog"
      sonar_project_key: "com.vtal.ms-resource-catalog"
      sonar_sources: "src"
      sonar_tests: ""
      sonar_exclusions: "**/*.md,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**"
      sonar_test_inclusions: "**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.jsx,**/*.spec.ts,**/*.spec.tsx"
      sonar_coverage: "coverage/lcov.info"

  releaseflow:
    name: Release Flow 🚀
    needs: [validate, sonar]
    if: >-
      ${{
        always() &&
        needs.validate.result == 'success' &&
        needs.validate.outputs.should_run == 'true' &&
        (
          needs.validate.outputs.should_run_sonar != 'true' ||
          needs.sonar.result == 'success'
        )
      }}
    secrets: inherit # pragma: allowlist secret
    uses: V-tal/shared-workflows/.github/workflows/releaseflow.yml@main
    with:
      runs_on: '["self-hosted","dev"]'
      trigger_event_name: ${{ github.event_name }}
      main_branch: "main"
      release_prefix: "release/"
      registry_repo: "ms-resource-catalog"
      release_name: "ms-resource-catalog"
      dockerfile: "Dockerfile"
      context: "."
      chart: "./helm"
      namespace_ti:  "microservicososs-ms-tmf634-resource-catalog-ti-qa"
      namespace_trg: "microservicososs-ms-tmf634-resource-catalog-trg-qa"
      namespace_prd: "microservicososs-ms-tmf634-resource-catalog-prod"
      value_files_ti:  "./helm/values_ti.yaml"
      value_files_trg: "./helm/values_trg.yaml"
      value_files_prd: "./helm/values_prd.yaml"
