appName: 'ms-resource-catalog'
image:
    ref: ''
    pullPolicy: IfNotPresent

serviceAccount:
    create: false
    name: ''
    annotations: {}
    automountServiceAccountToken: false

backstage:
    kubernetesId: 'ms-resource-catalog'

containerPort: 3000

service:
    port: 3000
    targetPort: http

registrySecret:
    create: false

envFrom:
    - configMapRef:
          name: ms-resource-catalog
    - secretRef:
          name: ms-resource-catalog

imagePullSecrets:
    - name: secret-nexus
    - name: secret-proxy

env:
    - name: DD_AGENT_HOST
      valueFrom:
          fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP

configMaps:
    application:
        name: ms-resource-catalog
        data:
            HOST_CERTS: 'https://ms-resource-catalog-trg.apps.ocparc-nprd.vtal.intra https://apilocaltrgv2.vtal.intra'

            APP_NAME: 'ms-resource-catalog'
            APP_HOST: 'https://ms-resource-catalog-trg.apps.ocparc-nprd.vtal.intra'
            DEBUG: 'false'
            NODE_ENV: 'production'
            PORT: '3000'
            API_ROUTE_PREFIX: 'api'
            CORS_ALLOWED_ORIGINS: '*'
            SWAGGER_ENABLED: 'true'
            SWAGGER_ALLOWED_METHODS: 'GET'
            SWAGGER_API_SERVER: ''
            SWAGGER_DESCRIPTION: 'Resource Catalog API is one of Catalog Management API Family. Resource Catalog API goal is to provide a catalog of resources.'

            DD_ENABLED: 'false'
            DD_ENV: 'trg'
            DD_SERVICE: 'ms-resource-catalog'
            DD_VERSION: '1.0.0'

            LOG_TYPE: 'logstash'
            LOG_LEVEL: 'trace'
            LOG_LEVEL_FILE: 'error'
            LOG_LEVEL_LOGSTASH: 'trace'
            LOG_LEVEL_TERMINAL: 'debug'
            LOG_LEVEL_RAW: 'trace'
            LOG_CONFIG_FILE: 'false'
            LOG_CONFIG_TERMINAL: 'true'
            LOG_CONFIG_NANOSECONDS: 'true'

            LOGSTASH_HOST: 'qelkqx01.elk.intra'
            LOGSTASH_PORT: '5044'
            LOGSTASH_INDEX: 'api-ms-resource-catalog-trg'
            LOGSTASH_SERVICE_PREFIX: 'ResourceCatalogManagement'
            LOGSTASH_RECOVERY: 'false'
            LOGSTASH_RECOVERY_QUEUE_MAX_SIZE: '1024'

            DATABASE_TYPE: 'mongodb'

            MONGODB_HOST: 'rctlqx01.local'
            MONGODB_PORT: '27020'
            MONGODB_NAME: 'catalogtrg'
            MONGODB_USER: 'catalogtrg'
            MONGODB_AUTH_SOURCE: 'admin'

            CACHE_TYPE: 'memory'
            CACHE_TTL: '3600000'
            CACHE_LIMIT: '5000'
            CACHE_PREFIX: 'ms-resource-catalog'
            REDIS_SECONDARY_STORE: 'false'

            RMQ_HOST: 'amqp://guest:guest@rabbitmq:5672'
            RMQ_EXCHANGE: 'ms-resource-catalog-x'
            RMQ_DEAD_LETTER_EXCHANGE: 'ms-resource-catalog-dlx'
            RMQ_DELAYED_EXCHANGE: 'true'
            RMQ_RETRY_DELAY: '120000'
            RMQ_RETRY_COUNT: '3'
            RMQ_PREFETCH_COUNT: '5'

            PORTAL_BACKEND_GUARD_ENABLED: 'true'

            INTEGRATION_JWT_ENABLED: 'true'
            JWT_ID: 'and0bXN0cmc='
            JWT_LOGIN: 'backmstrg'
            JWT_PASSWORD: 'KoG59zsBqfdNdpsGlzp#0354'

            INTEGRATION_APIGEE_ENABLED: 'true'
            INTEGRATION_APIGEE_URI: 'https://apilocaltrgv2.vtal.intra'

            RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT: 'Q_Notification_Dispatcher'
            RMQ_DLQ_MSG_TTL_NOTIFICATION_DISPATCHER_EVENT: '604800000'
            RMQ_DLQ_MAX_LENGTH_NOTIFICATION_DISPATCHER_EVENT: '1000'

route:
    enabled: true
    host: 'ms-resource-catalog-trg.apps.ocparc-nprd.vtal.intra'
    domain: 'apps.ocparc-nprd.vtal.intra'
    tls:
        enabled: true
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

resources:
    limits:
        cpu: 100m
        memory: 250Mi
    requests:
        cpu: 50m
        memory: 100Mi

probes:
    liveness:
        enabled: true
        httpGet:
            path: /health
            port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3

    readiness:
        enabled: true
        httpGet:
            path: /health
            port: 3000
        initialDelaySeconds: 20
        periodSeconds: 5
        failureThreshold: 6

    startup:
        enabled: true
        httpGet:
            path: /health
            port: 3000
        periodSeconds: 20
        failureThreshold: 5
        initialDelaySeconds: 2
        timeoutSeconds: 5

hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 80
    behavior:
        scaleUp:
            stabilizationWindowSeconds: 0
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 15
        scaleDown:
            stabilizationWindowSeconds: 300
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 15
