import { env } from '@/shared/infra/config/env/environment-config.service';

import { RmqPattern } from './message-broker-internal-patterns.const';

export const MESSAGE_BROKER_PATTERNS = {
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_CREATE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_CREATE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_STATUS_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_STATUS_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_ATTRIBUTE_VALUE_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_ATTRIBUTE_VALUE_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_DELETE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_DELETE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_CREATE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_CREATE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_STATUS_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_STATUS_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_ATTRIBUTE_VALUE_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_ATTRIBUTE_VALUE_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_DELETE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_DELETE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_CREATE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_CREATE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_STATUS_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_STATUS_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_ATTRIBUTE_VALUE_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_ATTRIBUTE_VALUE_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_CREATE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_CREATE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_STATUS_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_STATUS_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_ATTRIBUTE_VALUE_CHANGE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_ATTRIBUTE_VALUE_CHANGE}`,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_DELETE_EVENT: `${env('RMQ_QUEUE_NOTIFICATION_DISPATCHER_EVENT')}.${RmqPattern.NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_DELETE}`,
};
