export type {
  AdministrativeState,
  CreateLogicalResourceInput,
  CreatePhysicalResourceInput,
  CreateResourceFunctionSpecificationInput,
  CreateResourceSpecificationInput,
  ResourceCategory,
  LogicalResource,
  OperationalState,
  PhysicalResource,
  Resource,
  ResourceFunctionActivationInput,
  ResourceFunctionSpecification,
  ResourceFunctionSpecificationQuery,
  ResourceKind,
  ResourceQuery,
  ResourceRelationship,
  ResourceCatalog,
  ResourceCatalogNode,
  ResourceCatalogNodeKind,
  ResourceCatalogPath,
  ResourceCatalogPathEntry,
  ResourceCatalogQuery,
  ResourceCatalogTreeNode,
  ResourceTypeCatalogContext,
  ResourceTypeRef,
  CreateResourceCatalogInput,
  UpdateResourceCatalogInput,
  CreateResourceCatalogNodeInput,
  UpdateResourceCatalogNodeInput,
  MoveResourceCatalogNodeInput,
  ResourceType,
  ResourceSpecification,
  ResourceSpecificationBulkItem,
  ResourceSpecificationBulkItemResult,
  ResourceSpecificationBulkResult,
  ResourceSpecificationQuery,
  ResourceStatus,
  UpdateLogicalResourceInput,
  UpdatePhysicalResourceInput,
  UpdateResourceFunctionSpecificationInput,
  UpdateResourceSpecificationInput,
  UsageState,
} from './domain.js';
export type { IResourceRepository } from './resource-repository-interface.js';
export { ResourceRepository } from './repository.js';
export { PostgresResourceRepository } from './postgres-repository.js';
export { ResourceService } from './service.js';
