import { NotificationEvent } from '@/module/resource-catalog/domain/const/notification-event.const';

const RmqNotificationPattern = {
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_CREATE:
        NotificationEvent.RESOURCE_CATALOG_CREATE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_STATUS_CHANGE:
        NotificationEvent.RESOURCE_CATALOG_STATUS_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_ATTRIBUTE_VALUE_CHANGE:
        NotificationEvent.RESOURCE_CATALOG_ATTRIBUTE_VALUE_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATALOG_DELETE:
        NotificationEvent.RESOURCE_CATALOG_DELETE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_CREATE:
        NotificationEvent.RESOURCE_CATEGORY_CREATE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_STATUS_CHANGE:
        NotificationEvent.RESOURCE_CATEGORY_STATUS_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_ATTRIBUTE_VALUE_CHANGE:
        NotificationEvent.RESOURCE_CATEGORY_ATTRIBUTE_VALUE_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CATEGORY_DELETE:
        NotificationEvent.RESOURCE_CATEGORY_DELETE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_CREATE:
        NotificationEvent.RESOURCE_CANDIDATE_CREATE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_STATUS_CHANGE:
        NotificationEvent.RESOURCE_CANDIDATE_STATUS_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_CANDIDATE_ATTRIBUTE_VALUE_CHANGE:
        NotificationEvent.RESOURCE_CANDIDATE_ATTRIBUTE_VALUE_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_CREATE:
        NotificationEvent.RESOURCE_SPECIFICATION_CREATE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_STATUS_CHANGE:
        NotificationEvent.RESOURCE_SPECIFICATION_STATUS_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_ATTRIBUTE_VALUE_CHANGE:
        NotificationEvent.RESOURCE_SPECIFICATION_ATTRIBUTE_VALUE_CHANGE_EVENT,
    NOTIFICATION_DISPATCHER_RESOURCE_SPECIFICATION_DELETE:
        NotificationEvent.RESOURCE_SPECIFICATION_DELETE_EVENT,
} as const;

export const RmqPattern = {
    ...RmqNotificationPattern,
} as const;

export type RmqPattern = (typeof RmqPattern)[keyof typeof RmqPattern];
export type RmqNotificationPattern =
    (typeof RmqNotificationPattern)[keyof typeof RmqNotificationPattern];
