{{- $serviceAccount := .Values.serviceAccount | default dict -}}
{{- if ($serviceAccount.create | default true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app.serviceAccountName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ include "app.label" . | quote }}
  annotations:
    backstage.io/kubernetes-id: {{ include "app.backstageKubernetesId" . }}
    {{- with $serviceAccount.annotations }}
{{ toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ $serviceAccount.automountServiceAccountToken | default false }}
{{- $imagePullSecrets := .Values.imagePullSecrets | default list -}}
{{- if gt (len $imagePullSecrets) 0 }}
imagePullSecrets:
{{ toYaml $imagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
