apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app: {{ include "app.label" . | quote }}
  annotations:
    backstage.io/kubernetes-id: {{ include "app.backstageKubernetesId" . }}
spec:
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app: {{ include "app.label" . | quote }}
  ports:
    {{- $service := .Values.service | default dict }}
    - name: http
      port: {{ $service.port | default 8080 }}
      targetPort: {{ $service.targetPort | default "http" }}
      protocol: TCP
